letsramp/helm

- charts/mongo-datastore/Chart.yaml
- charts/mongo-datastore/templates/mongo-cr.yaml
Test case
```
$ skyramp deployer up dashboard -v
INFO Setting log level to Info                    
INFO Project path is                              
INFO Validate license                              module=licensing
INFO Running deployer up command with target dashboard  cmd=up
INFO Reading project directory                     module=loader
INFO Added target dashboard.yaml to project        module=loader
INFO No dependency errors                          module=loader
INFO validation passed                             module=loader
INFO namespace skyramp does not exist             
INFO namespace skyramp does not exist             
INFO Using 296613639307.dkr.ecr.us-west-2.amazonaws.com/dev/worker:bbb56774 for worker image  cmd=up
INFO builder option: &{true} …
```
> Add manifest to template

- charts/web-server/Chart.yaml
for https://github.com/letsramp/web-server/pull/16
> bumping up  dashboard version

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.40
> Update Helm Skyramp Worker to v0.4.40

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.41
> Update Helm Skyramp Worker to v0.4.41

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.42
> Update Helm Skyramp Worker to v0.4.42

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.43
> Update Helm Skyramp Worker to v0.4.43

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.44
> Update Helm Skyramp Worker to v0.4.44

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.45
> Update Helm Skyramp Worker to v0.4.45

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.46
> Update Helm Skyramp Worker to v0.4.46

- charts/web-server/Chart.yaml
https://github.com/letsramp/web-server/pull/18
> dashboard version bump

- charts/web-server/Chart.yaml
- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.47
> Update Helm Skyramp Worker to v0.4.47

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.48
> Update Helm Skyramp Worker to v0.4.48

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.49
> Update Helm Skyramp Worker to v0.4.49

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.50
> Update Helm Skyramp Worker to v0.4.50

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.51
> Update Helm Skyramp Worker to v0.4.51

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.52
> Update Helm Skyramp Worker to v0.4.52

- charts/web-server/Chart.yaml
https://github.com/letsramp/web-server/commit/6e9bc3f424f4bf1cdba03909645fe7611ad53edb
> updating dashboard version

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.53
> Update Helm Skyramp Worker to v0.4.53

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.54
> Update Helm Skyramp Worker to v0.4.54

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.55
> Update Helm Skyramp Worker to v0.4.55

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.56
> Update Helm Skyramp Worker to v0.4.56

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.57
> Update Helm Skyramp Worker to v0.4.57

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.59
> Update Helm Skyramp Worker to v0.4.59

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.60
> Update Helm Skyramp Worker to v0.4.60

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.61
> Update Helm Skyramp Worker to v0.4.61

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.62
> Update Helm Skyramp Worker to v0.4.62

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.63
> Update Helm Skyramp Worker to v0.4.63

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.64
> Update Helm Skyramp Worker to v0.4.64

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.65
> Update Helm Skyramp Worker to v0.4.65

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.66
> Update Helm Skyramp Worker to v0.4.66

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.67
> Update Helm Skyramp Worker to v0.4.67

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.68
> Update Helm Skyramp Worker to v0.4.68

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.69
> Update Helm Skyramp Worker to v0.4.69

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.70
> Update Helm Skyramp Worker to v0.4.70

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.72
> Update Helm Skyramp Worker to v0.4.72

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.73
> Update Helm Skyramp Worker to v0.4.73

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.74
> Update Helm Skyramp Worker to v0.4.74

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.75
> Update Helm Skyramp Worker to v0.4.75

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.76
> Update Helm Skyramp Worker to v0.4.76

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.77
> Update Helm Skyramp Worker to v0.4.77

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.78
> Update Helm Skyramp Worker to v0.4.78

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.79
> Update Helm Skyramp Worker to v0.4.79

- charts/web-server/Chart.yaml
https://github.com/letsramp/web-server/pull/27
> version bump

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.80
> Update Helm Skyramp Worker to v0.4.80

- charts/web-server/Chart.yaml
- charts/web-server/values.yaml
- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.81
> Update Helm Skyramp Worker to v0.4.81

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.82
> Update Helm Skyramp Worker to v0.4.82

- charts/web-server/Chart.yaml
https://github.com/letsramp/web-server/pull/34
> Dashboard version bump v1.0.18

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.84
> Update Helm Skyramp Worker to v0.4.84

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.85
> Update Helm Skyramp Worker to v0.4.85

- charts/web-server/Chart.yaml
https://github.com/letsramp/web-server/actions/runs/9294927570
> Dashboard version bump v1.0.21

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.86
> Update Helm Skyramp Worker to v0.4.86

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.87
> Update Helm Skyramp Worker to v0.4.87

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.88
> Update Helm Skyramp Worker to v0.4.88

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.89
> Update Helm Skyramp Worker to v0.4.89

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.90
> Update Helm Skyramp Worker to v0.4.90

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.91
> Update Helm Skyramp Worker to v0.4.91

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.92
> Update Helm Skyramp Worker to v0.4.92

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.93
> Update Helm Skyramp Worker to v0.4.93

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.94
> Update Helm Skyramp Worker to v0.4.94

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.95
> Update Helm Skyramp Worker to v0.4.95

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.96
> Update Helm Skyramp Worker to v0.4.96

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.97
> Update Helm Skyramp Worker to v0.4.97

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.98
> Update Helm Skyramp Worker to v0.4.98

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.99
> Update Helm Skyramp Worker to v0.4.99

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.100
> Update Helm Skyramp Worker to v0.4.100

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.101
> Update Helm Skyramp Worker to v0.4.101

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.102
> Update Helm Skyramp Worker to v0.4.102

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.104
> Update Helm Skyramp Worker to v0.4.104

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.105
> Update Helm Skyramp Worker to v0.4.105

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.4.106
> Update Helm Skyramp Worker to v0.4.106

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.3
> Update Helm Skyramp Worker to v0.5.3

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.4
> Update Helm Skyramp Worker to v0.5.4

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.5
> Update Helm Skyramp Worker to v0.5.5

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.6
> Update Helm Skyramp Worker to v0.5.6

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.7
> Update Helm Skyramp Worker to v0.5.7

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.8
> Update Helm Skyramp Worker to v0.5.8

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.9
> Update Helm Skyramp Worker to v0.5.9

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.10
> Update Helm Skyramp Worker to v0.5.10

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.11
> Update Helm Skyramp Worker to v0.5.11

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.12
> Update Helm Skyramp Worker to v0.5.12

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.13
> Update Helm Skyramp Worker to v0.5.13

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.15
> Update Helm Skyramp Worker to v0.5.15

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.16
> Update Helm Skyramp Worker to v0.5.16

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.17
> Update Helm Skyramp Worker to v0.5.17

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.20
> Update Helm Skyramp Worker to v0.5.20

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.22
> Update Helm Skyramp Worker to v0.5.22

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.23
> Update Helm Skyramp Worker to v0.5.23

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.24
> Update Helm Skyramp Worker to v0.5.24

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v0.5.25
> Update Helm Skyramp Worker to v0.5.25

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.3
> Update Helm Skyramp Worker to v1.2.3

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.6
> Update Helm Skyramp Worker to v1.2.6

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.7
> Update Helm Skyramp Worker to v1.2.7

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.10
> Update Helm Skyramp Worker to v1.2.10

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.11
> Update Helm Skyramp Worker to v1.2.11

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to 1.2.12
> Update Helm Skyramp Worker to 1.2.12

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.13
> Update Helm Skyramp Worker to v1.2.13

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.15
> Update Helm Skyramp Worker to v1.2.15

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.17
> Update Helm Skyramp Worker to v1.2.17

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.19
> Update Helm Skyramp Worker to v1.2.19

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.20
> Update Helm Skyramp Worker to v1.2.20

- charts/worker/Chart.yaml
Update Helm Skyramp Worker to v1.2.24
> Update Helm Skyramp Worker to v1.2.24
